# Generated by Django 2.0.5 on 2018-05-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180523_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
