# Generated by Django 2.0.5 on 2018-05-28 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0009_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.ManyToManyField(default=None, related_name='a_disliked_from', to=settings.AUTH_USER_MODEL, verbose_name='a_disliked from'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='a_liked_from', to=settings.AUTH_USER_MODEL, verbose_name='a_liked from'),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.ManyToManyField(default=None, related_name='q_disliked_from', to=settings.AUTH_USER_MODEL, verbose_name='q_disliked from'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='q_liked_from', to=settings.AUTH_USER_MODEL, verbose_name='q_liked from'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
