# Generated by Django 2.0.5 on 2018-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
