# Generated by Django 2.0.5 on 2018-06-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20180611_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='is_used',
        ),
        migrations.AddField(
            model_name='invite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
